# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de6c74ffb4ee27a1932ce1744dfccf8c4daf425372960ba6839cd047e430be4792cddf199be67fdf49513602ed66f34b977f5979599a74673f39d978fbe05c08

test:
  secret_key_base: 645844a66dacc1b2c5331167e64b5fc4dc5931c05b966fbd914be1ced9d159a700095f65c95d3e6f1f596b209e5fe5abe19efc9864bdda6cf6d2968e238b34fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
